### ISSUE TITLE
Use ruby instead

### ISSUE THREAD

**Issue by sobrinho** [norbajunior/my_elixir#1]
Ruby would allow you to do that natively:

``` ruby
[2,4,6].all? { |i| i % 2 == 0 }

[2,4,6].each { |i| puts i }

[2,4,6].filter { |i| i < 5 }
```

**Comment by norbajunior** [comment]
@sobrinho Elixir already have this natively as well.

**Comment by norbajunior** [comment]
This is just to practice the functional paradigm, trying to exercise your mind rewriting those functions. Just for fun

**Comment by norbajunior** [comment]
🙄🙄

**Comment by sobrinho** [comment]
I prefer ruby, #justsaying.

**Comment by sobrinho** [comment]
Ruby is... 
![1e316e8b30384c27aa347055973c419a658e6673e630d193304482261ef5de28](https://cloud.githubusercontent.com/assets/26460/23320650/70bdf96c-faba-11e6-9219-81364ebd4bcc.jpg)

**Comment by rafafelix0** [comment]
close please, *troll detected*

**Comment by norbajunior** [comment]
![http://i0.kym-cdn.com/photos/images/facebook/000/993/875/084.png](http://i0.kym-cdn.com/photos/images/facebook/000/993/875/084.png)
